
install.packages('ropenaq')
library(ropenaq)
library(tidyverse)
library(rvest)
library(lubridate)
library(stringr)
library(tidytext)
library(knitr)
library(choroplethr)
library(choroplethrMaps)

countries = aq_countries()
US_latest = aq_latest(country = 'US', parameter = 'pm25')
glimpse(US_latest)